"""empty message

Revision ID: 44e4069e0a9f
Revises: 
Create Date: 2020-04-01 17:26:30.099492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44e4069e0a9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='user')
    op.drop_index('name', table_name='user')
    op.drop_index('phone', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('pwd', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('age', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('sex', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('job', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('experience', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('test', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('create_time', mysql.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('phone', 'user', ['phone'], unique=True)
    op.create_index('name', 'user', ['name'], unique=True)
    op.create_index('id', 'user', ['id'], unique=True)
    # ### end Alembic commands ###
